spring.application.name=ToDo
server.port=8080
server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/toDo
spring.datasource.username=postgres
spring.jpa.show-sql=true