spring.application.name=ToDo
server.port=8080
server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/todo
spring.datasource.username=yusufsami
spring.jpa.show-sql=true

jwt-secret="C6UlILsE6GJwNqwCTkkvJj9O653yJUoteWMLfYyrc3vaGrrTOrJFAUD1wEBnnposzcQl"
jwt-expiration-ms=86400000